identity_providers:
  oidc:
    authorization_policies:
      immich_user:
        default_policy: deny
        rules:
          - policy: 'one_factor'
            subject: 'group:immich_user'
    clients:
      - client_id: '{{ env "OIDC_IMMICH_CLIENT_ID" }}'
        client_name: 'immich'
        client_secret: '{{ secret "/run/secrets/oidc_immich_digest" }}'
        public: false
        authorization_policy: 'immich_user' # immich does not have its own RBAC
        redirect_uris:
          - '{{ expandenv "https://${IMMICH_SUBDOMAIN}.${CF_DOMAIN_NAME}/auth/login" }}'
          - '{{ expandenv "https://${IMMICH_SUBDOMAIN}.${CF_DOMAIN_NAME}/user-settings" }}'
          - 'app.immich:///oauth-callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'