{
 "title": "Prometheus",
 "description": "Almost all internal Prometheus metrics",
 "tags": [ "apps" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "monitor",
    "label": "Monitor",
    "query": {
     "query": "label_values(prometheus_build_info,monitor)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ready",
   "type": "stat",
   "description": "Whether Prometheus startup was fully completed and the server is ready for normal operation.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{monitor=\"$monitor\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "Number of scrape pool targets.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_targets{monitor=\"$monitor\"})",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "description": "Total user and system CPU time.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{monitor=\"$monitor\"}[$__rate_interval]))/scalar(count(node_cpu_seconds_total{monitor=\"$monitor\",mode=\"idle\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Resident memory size.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{monitor=\"$monitor\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{monitor=\"$monitor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "stat",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{monitor=\"$monitor\"})",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Oldest Value",
   "type": "stat",
   "description": "Oldest timestamp value stored in the database.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(prometheus_tsdb_lowest_timestamp_seconds)-prometheus_tsdb_lowest_timestamp_seconds{monitor=\"$monitor\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{monitor=\"$monitor\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Failing",
   "type": "stat",
   "description": "Number of scrape jobs that are unhealthy",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{monitor=\"$monitor\"} < 1) or vector(0)",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "stat",
   "description": "State of the query log.\nhttps://prometheus.io/docs/guides/query-log/",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_query_log_enabled{monitor=\"$monitor\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Log Failures",
   "type": "stat",
   "description": "The number of query log failures.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_log_failures_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "The current number of queries being executed or waiting.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_queries{monitor=\"$monitor\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{monitor=\"$monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\", monitor=\"$monitor\"}"
    }
   ]
  },
  {
   "title": "Scrape Job Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "up{monitor=\"$monitor\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Prometheus CPU Usage %",
   "type": "timeseries",
   "description": "Total user and system CPU time of Prometheus process.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{monitor=\"$monitor\"}[$__rate_interval])/scalar(count(node_cpu_seconds_total{monitor=\"$monitor\",mode=\"idle\"}))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Prometheus RAM Usage",
   "type": "timeseries",
   "description": "Resident memory size of Prometheus process",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{monitor=\"$monitor\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  { "title": "Head Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "# of Series",
   "type": "timeseries",
   "description": "Total number of series in the head block.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{monitor=\"$monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series Churn",
   "type": "timeseries",
   "description": "Total number of series created/removed in the head",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_series_created_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "created"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_removed_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Time Bounds",
   "type": "timeseries",
   "description": "Minumum and maximum timestamp of the head block.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "timestamp(prometheus_tsdb_head_max_time_seconds{monitor=\"$monitor\"})-prometheus_tsdb_head_max_time_seconds{monitor=\"$monitor\"}",
     "legendFormat": "max"
    },
    {
     "expr": "timestamp(prometheus_tsdb_head_min_time_seconds{monitor=\"$monitor\"})-prometheus_tsdb_head_min_time_seconds{monitor=\"$monitor\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Samples Appended",
   "type": "timeseries",
   "description": "Total number of appended samples.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Chunks in Head",
   "type": "timeseries",
   "description": "Total number of chunks in the head block.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{monitor=\"$monitor\"}",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Chunks Churn",
   "type": "timeseries",
   "description": "Total number of chunks created/removed in the head",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "created"
    },
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Active Appenders",
   "type": "timeseries",
   "description": "Number of currently active appender transactions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Truncations",
   "type": "stat",
   "description": "Total number of head truncations attempted.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_truncations_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Samples OOO"
    }
   ]
  },
  {
   "title": "Failed Truncations",
   "type": "stat",
   "description": "Total number of head truncations that failed.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_truncations_failed_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Samples OOO"
    }
   ]
  },
  {
   "title": "Series Not Found",
   "type": "stat",
   "description": "Total number of requests for series that were not found.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_series_not_found_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Samples OOO"
    }
   ]
  },
  {
   "title": "Samples Out of Order",
   "type": "stat",
   "description": "Total number of appended out of order samples.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_head_out_of_order_samples_appended_total{monitor=\"$monitor\"}[$__range]))",
     "legendFormat": "Samples OOO"
    }
   ]
  },
  { "title": "Scrape", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Scrape Job Status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "up{monitor=\"$monitor\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Duplicate Rejected",
   "type": "stat",
   "description": "Total number of samples rejected due to duplicate timestamps but different values.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Samples Out of Order",
   "type": "stat",
   "description": "Total number of samples rejected due to not being out of the expected order.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Exemplars Out of Order",
   "type": "stat",
   "description": "Total number of exemplar rejected due to not being out of the expected order.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_exemplar_out_of_order_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pool Creation Attempts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrape_pools_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pool Reloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrape_pool_reloads_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Sample Limit Hits",
   "type": "stat",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Label Limit Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrape_pool_exceeded_label_limits_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Metadata Cache",
   "type": "stat",
   "description": "Metric metadata in the cache for target scraping.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_metadata_cache_bytes{monitor=\"$monitor\"})",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Cache Force Flushes",
   "type": "stat",
   "description": "How many times a scrape cache was flushed due to getting big while scrapes are failing.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_cache_flush_forced_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Samples Out of Bounds",
   "type": "stat",
   "description": "Total number of samples rejected due to timestamp falling outside of the time bounds.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Target Sync Failure",
   "type": "stat",
   "description": "Total number of target sync failures.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_sync_failed_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pool Creation Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrape_pools_failed_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pool Reload Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrape_pool_reloads_failed_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Body Size Limit Hits",
   "type": "stat",
   "description": "Total number of scrapes that hit the body size limit",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_body_size_limit_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Target Limit Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrape_pool_exceeded_target_limit_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pool Syncs",
   "type": "stat",
   "description": "Average number syncs executed on scrape pools between all jobs.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(prometheus_target_scrape_pool_sync_total{monitor=\"$monitor\"}[$__range]))"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Query Duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{monitor=\"$monitor\",quantile=\"0.9\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Query Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{monitor=\"$monitor\",quantile=\"0.99\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "HTTP Latency (/metrics)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_request_duration_seconds_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Size (/metrics)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_response_size_bytes_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Remote Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Samples Rate",
   "type": "timeseries",
   "description": "Samples incoming/sent to Remote Storage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_in_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "IN"
    },
    {
     "expr": "rate(prometheus_remote_storage_samples_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Remote Sent Rate",
   "type": "timeseries",
   "description": "The total number of bytes of data (not metadata) sent by the queue after compression. Note that when exemplars over remote write is enabled the exemplars included in a remote write request count towards this metric.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_bytes_total{monitor=\"$monitor\"}[$__rate_interval]))",
     "legendFormat": "Sent Bytes"
    }
   ]
  },
  {
   "title": "Send Batch Duration",
   "type": "heatmap",
   "description": "Duration of send calls to the remote storage.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_remote_storage_sent_batch_duration_seconds_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Appender Lag",
   "type": "timeseries",
   "description": "Highest timestamp that has come into the remote storage via the Appender interface.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - prometheus_remote_storage_highest_timestamp_in_seconds{monitor=\"$monitor\"}",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Remote Storage Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_bytes_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(prometheus_remote_storage_enqueue_retries_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "prometheus_remote_storage_max_samples_per_send{monitor=\"$monitor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prometheus_remote_storage_samples_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prometheus_remote_storage_samples_dropped_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prometheus_remote_storage_samples_failed_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prometheus_remote_storage_samples_retried_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "prometheus_remote_storage_samples_pending{monitor=\"$monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Incoming Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Accepted Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "{{listener_name}}"
    }
   ]
  },
  {
   "title": "Listener Closed Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 137 },
   "targets": [
    {
     "expr": "rate(net_conntrack_listener_conn_closed_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "{{listener_name}}"
    }
   ]
  },
  { "title": "Outgoing Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Established Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_established_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Connection Attempts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_attempted_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Refused Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_failed_total{monitor=\"$monitor\",reason=\"refused\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Closed Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 157 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_closed_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Resolution Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_failed_total{monitor=\"$monitor\",reason=\"resolution\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Timed-out Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_failed_total{monitor=\"$monitor\",reason=\"timeout\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Unknown Connection Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_failed_total{monitor=\"$monitor\",reason=\"unknown\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  { "title": "WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "Page Completion/Flush Rate",
   "type": "timeseries",
   "description": "Page completion/flush rate.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_completed_pages_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "completed"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_page_flushes_total{monitor=\"$monitor\"}[$__rate_interval])",
     "legendFormat": "flushes"
    }
   ]
  },
  {
   "title": "WAL fsync Duration",
   "type": "timeseries",
   "description": "Duration (p99) of write log fsync.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_fsync_duration_seconds{monitor=\"$monitor\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Truncations",
   "type": "stat",
   "description": "Total number of write log truncations attempted.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 197 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_truncations_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Failed Truncations",
   "type": "stat",
   "description": "Total number of write log truncations that failed.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 197 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_truncations_failed_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Corruptions",
   "type": "stat",
   "description": "Total number of WAL corruptions.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 197 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_corruptions_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Failed Writes",
   "type": "stat",
   "description": "Total number of write log writes that failed.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 197 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_writes_failed_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Watcher Records Failed",
   "type": "stat",
   "description": "Number of records read by the WAL watcher that resulted in an error when decoding.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 197 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_wal_watcher_record_decode_failures_total{monitor=\"$monitor\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TSDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 } },
  {
   "title": "Local Storage",
   "type": "timeseries",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{monitor=\"$monitor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoints Deleted",
   "type": "stat",
   "description": "Total number of checkpoint deletions attempted.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_deletions_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Checkpoints Created",
   "type": "stat",
   "description": "Total number of checkpoint creations attempted.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_creations_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Data Blocks",
   "type": "stat",
   "description": "Number of currently loaded data blocks",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 203 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{monitor=\"$monitor\"}"
    }
   ]
  },
  {
   "title": "Vertical Compactions",
   "type": "stat",
   "description": "Total number of compactions done on overlapping blocks.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 203 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_vertical_compactions_total{monitor=\"$monitor\"}[$__range])"
    }
   ]
  },
  {
   "title": "Checkpoint Del Failures",
   "type": "stat",
   "description": "Total number of checkpoint deletions that failed.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 208 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_deletions_failed_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Checkpoint Create Failures",
   "type": "stat",
   "description": "Total number of checkpoint creations that failed.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 208 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_creations_failed_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "TSDB Clean Start",
   "type": "stat",
   "description": "Lockfile state from previous execution: CLEAN (no lockfile), REPLACED (lockfile replaced), DISABLED (lockfile disabled).",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_clean_start{monitor=\"$monitor\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Replay Time",
   "type": "stat",
   "description": "Time taken to replay the data on disk.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_data_replay_duration_seconds{monitor=\"$monitor\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Symbol Table RAM",
   "type": "stat",
   "description": "Size of symbol table in memory for loaded blocks",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_symbol_table_size_bytes{monitor=\"$monitor\"}"
    }
   ]
  },
  {
   "title": "MMap Corruptions",
   "type": "stat",
   "description": "Total number of memory-mapped chunk corruptions.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 213 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_mmap_chunk_corruptions_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Reload Failures",
   "type": "stat",
   "description": "Number of times the database failed to reloadBlocks block data from disk.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 213 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_reloads_failures_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Snapshot Replay Errors",
   "type": "stat",
   "description": "Total number snapshot replays that failed.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 213 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_snapshot_replay_error_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Samples Out of Time",
   "type": "stat",
   "description": "Total number of out of order samples ingestion failed attempts with out of support enabled, but sample outside of time window.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_too_old_samples_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Time Retention Hits",
   "type": "stat",
   "description": "The number of times that blocks were deleted because the maximum time limit was exceeded.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_time_retentions_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Size Retention Hits",
   "type": "stat",
   "description": "The number of times that blocks were deleted because the maximum number of bytes was exceeded.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_size_retentions_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Size Retention Limit",
   "type": "stat",
   "description": "Max number of bytes to be retained in the tsdb blocks.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_retention_limit_bytes{monitor=\"$monitor\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  { "title": "TSDB Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Compaction Duration",
   "type": "heatmap",
   "description": "Duration of compaction runs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 219 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_compaction_duration_seconds_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Compaction Chunk Size",
   "type": "heatmap",
   "description": "Final size of chunks on their first compaction",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 219 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Compaction Chunk Samples",
   "type": "heatmap",
   "description": "Final number of samples on their first compaction",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_compaction_chunk_samples_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Compaction Chunk Time Range",
   "type": "heatmap",
   "description": "Final time range of chunks on their first compaction",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_compaction_chunk_range_seconds_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Triggered",
   "type": "stat",
   "description": "Total number of triggered compactions for the partition.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 236 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_triggered_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Executed",
   "type": "stat",
   "description": "Total number of compactions that were executed for the partition.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 236 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Total number of compactions that failed for the partition.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 236 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_failed_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Skipped",
   "type": "stat",
   "description": "Total number of skipped compactions due to disabled auto compaction.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 236 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_skipped_total{monitor=\"$monitor\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Tombstone Cleanup Duration",
   "type": "heatmap",
   "description": "The time taken to recompact blocks to remove tombstones.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 236 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_tombstone_cleanup_seconds_bucket{monitor=\"$monitor\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}