{
 "title": "Storage",
 "description": "Extended smartctl-exporter Dashboard",
 "tags": [ "system" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "monitor",
    "label": "Monitor",
    "query": {
     "query": "label_values(smartctl_version,monitor)"
    }
   },
   {
    "name": "horizon",
    "label": "Time Horizon",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{monitor=\"$monitor\"},mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(present_over_time(smartctl_device_smart_status{monitor=\"$monitor\"}[$horizon]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(smartctl_device_smart_status{monitor=\"$monitor\"}[$horizon]) != 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wear Level on SSD Devices",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(100 - last_over_time(smartctl_device_attribute{monitor=\"$monitor\", attribute_name=\"Wear_Leveling_Count\",attribute_value_type=\"value\"}[$horizon]) * on(monitor, device) group_left(interface,serial_number,model_family,model_name) present_over_time(smartctl_device{interface=~\"sat\"}[$horizon]))",
     "legendFormat": "{{model_name}} ({{device}})"
    },
    {
     "expr": "sort_desc(100 - last_over_time(smartctl_device_attribute{monitor=\"$monitor\", attribute_name=\"SSD_Life_Left\",attribute_value_type=\"value\"}[$horizon]) * on(monitor, device) group_left(interface,serial_number,model_family,model_name) present_over_time(smartctl_device{interface=~\"sat\"}[$horizon]))",
     "legendFormat": "{{model_name}} ({{device}})"
    },
    {
     "expr": "sort_desc(smartctl_device_percentage_used{monitor=\"$monitor\"} * on(monitor, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=\"nvme\"})",
     "legendFormat": "{{model_name}} ({{device}})"
    }
   ]
  },
  { "title": "Mountpoint Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{monitor=\"$monitor\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{monitor=\"$monitor\", mountpoint=~\"$mountpoint\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Used Bytes Delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(node_filesystem_avail_bytes{monitor=~\"$monitor\", mountpoint=~\"$mountpoint\"}[$__rate_interval]) * -1",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "HDD Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{monitor=\"$monitor\"} * on(monitor, device) group_left(interface,serial_number,model_name) smartctl_device) by (monitor,device,model_name) and on(monitor, device) (smartctl_device_attribute{attribute_name=\"Start_Stop_Count\", attribute_value_type=\"raw\"} > 0)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "SSD Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{monitor=\"$monitor\"} * on(monitor, device) group_left(interface,serial_number,model_name) smartctl_device) by (monitor,device,model_name) unless on(monitor, device) (smartctl_device_attribute{attribute_name=\"Start_Stop_Count\", attribute_value_type=\"raw\"} > 0)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Data Written Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_disk_written_bytes_total{monitor=\"$monitor\"} > 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{monitor=\"$monitor\"}[$__rate_interval]) > 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Lifetime",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max(last_over_time(smartctl_device_power_on_seconds{monitor=\"$monitor\"}[$horizon]) * on(monitor, device) group_left(interface,serial_number,model_family,model_name) present_over_time(smartctl_device[$horizon])) by (monitor, device, model_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(last_over_time(smartctl_device_power_cycle_count{monitor=\"$monitor\"}[$horizon]) * on(monitor, device) group_left(interface,serial_number,model_family,model_name) present_over_time(smartctl_device[$horizon])) by (monitor, device, model_name)",
     "legendFormat": "Power Cycles"
    }
   ]
  },
  {
   "title": "Total Data Written on SSDs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max(smartctl_device_bytes_written{monitor=\"$monitor\"} * on(monitor, device) group_left(interface,serial_number,model_family,model_name) smartctl_device) by (device, monitor, model_name, serial_number)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(last_over_time(smartctl_device_attribute{monitor=\"$monitor\", attribute_name=\"Lifetime_Writes_GiB\", attribute_value_type=\"raw\"}[$horizon]) * 1000000000 * on(monitor, device) group_left(interface,serial_number,model_family,model_name) present_over_time(smartctl_device[$horizon])) by (device, monitor, model_name, serial_number)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((last_over_time(smartctl_device_attribute{monitor=\"$monitor\", attribute_name=\"Total_LBAs_Written\", attribute_value_type=\"raw\"}[$horizon]) * on (monitor,device) last_over_time(smartctl_device_block_size{monitor=\"$monitor\",blocks_type=\"physical\"}[$horizon])) * on(monitor, device) group_left(interface,serial_number,model_family,model_name) present_over_time(smartctl_device[$horizon])) by (device, monitor, model_name, serial_number)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}