services:
  prometheus:
    networks:
      - homepage
  grafana:
    labels:
      homepage.group: System
      homepage.name: Grafana
      homepage.description: Dashboards and logs for monitoring
      homepage.icon: sh-grafana
      homepage.href: https://${GRAFANA_SUBDOMAIN}.${CF_DOMAIN_NAME}/
      homepage.widget.type: prometheusmetric
      homepage.widget.url: http://prometheus:9090
      homepage.widget.refreshInterval: 5000
      homepage.widget.metrics[0].label: Errors
      homepage.widget.metrics[0].query: ceil(sum(increase(self_host_log_lines_total{level="error",monitor="${HOSTNAME}"}[10m])))
      homepage.widget.metrics[1].label: Warnings
      homepage.widget.metrics[1].query: ceil(sum(increase(self_host_log_lines_total{level="warn",monitor="${HOSTNAME}"}[10m])))