identity_providers:
  oidc:
    authorization_policies:
      nextcloud_user:
        default_policy: deny
        rules:
          - policy: 'one_factor'
            subject: 'group:nextcloud_user'
    clients:
      - client_id: {{ env "OIDC_NEXTCLOUD_CLIENT_ID" }}
        client_name: 'nextcloud'
        client_secret: {{ secret "/run/secrets/oidc_nextcloud_digest" }}
        public: false
        authorization_policy: 'nextcloud_user' # nextcloud does not have its own RBAC
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - {{ expandenv "https://nextcloud.${CF_DOMAIN_NAME}/apps/user_oidc/code" }}
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'