name: Build Resources

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate ZIP files for appdata folders
        run: |
          mkdir -p appdata_zips  # Temporary folder to store ZIP files
          appdata_zips=$(pwd)/appdata_zips
          
          find . -type d -name "appdata" | while read dir; do
            parent_dir=$(dirname "$dir")  # Get the parent folder of "appdata"
            zip_name=$(basename "$parent_dir").zip  # Format: {folder}.zip
            
            echo "Creating ZIP: $zip_name"
            (cd "$dir" && zip -r "$appdata_zips/$zip_name" .)  # Zip contents, not the folder itself
          done

      - name: Upload ZIP files
        uses: actions/upload-artifact@v4
        with:
          name: appdata_zips
          path: appdata_zips

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download ZIP files
        uses: actions/download-artifact@v4
        with:
          name: appdata_zips
          path: appdata

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          git add appdata/
          git commit -m "Update Resources"
          git push -f origin gh-pages